language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t carolli/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true carolli/docker-react npm run test
